app/page.tsx, components/sections/WhatWeDo.tsx
=> fix: :lipstick: Fix alignment of home page sections

config/projects.ts
=> adjusting the link in project detail

app/page.tsx, app/projects/[id]/page.tsx, app/projects/page.tsx, components/site-footer.tsx, components/svgs/arrows.tsx, components/svgs/social-medias.tsx, config/projects.ts, config/site.ts
=> Fix links verification on ProjectDetail/ProjectsLibrary pages 

app/layout.tsx, app/page.tsx, app/projects/[id]/page.tsx, app/projects/page.tsx, components/main-nav.tsx, components/sections/News.tsx, components/site-footer.tsx, components/site-header-mobile.tsx, components/site-header.tsx, data/news.ts, data/projects.ts, lib/types.ts, styles/globals.css, tailwind.config.js
- Refactor news items into its own component
- Add `data/news.ts` to hold news items
- Create `NewsInterface` to keep news items consistent
- Add hover styles & animations to news items
- Add animation to main heading
- Refactor responsive text sizes in header and news sections
- Add subtle shadow to nav
- Add heading to news items: "What's Happening"
- Add underline animation for nav items for consistency
- Update SEO for projects & project details
- Update project images
- Update styles on project detail page
=> Refactor News section

data/news.ts
add 2 learn and share, detail point to discord events
=> Add Aug learn and share

data/news.ts
add 2 events in Aug, link to discord
=> Adding Aug learn and share to home page

app/layout.tsx
This PR adds Matomo analytics 
ref: https://github.com/privacy-scaling-explorations/website-v2/issues/42
=> insert matomo analytic to the site

data/projects/anon-aadhaar.ts, data/projects/anon-klub.ts, data/projects/bandada.ts, data/projects/channel-4.ts, data/projects/cryptkeeper.ts, data/projects/discreetly.ts, data/projects/dsl-working-group.ts, data/projects/eigen-trust.ts, data/projects/maci.ts, data/projects/pollen-labs.ts, data/projects/pse-security.ts, data/projects/rln.ts, data/projects/semaphore.ts, data/projects/summa.ts, data/projects/tlsn.ts, data/projects/trusted-setups.ts, data/projects/unirep-protocol.ts, data/projects/wax.ts, data/projects/zk3.ts, data/projects/zkevm-community.ts, data/projects/zkitter.ts, data/projects/zkml.ts, data/projects/zkp2p.ts, lib/types.ts
add `project status` to the project list & small fixes in the project list
=> update project tags

app/projects/[id]/page.tsx, components/icons.tsx, components/project/project-card.tsx, components/project/project-list.tsx, components/ui/categoryTag.tsx, lib/utils.ts, state/useProjectFiltersState.ts
=> add projects suggestions

app/content/resources.md
=> adding good first issue

data/projects/discreetly.ts
Updated discreetly to remove waku and include the website link
=> Discreetly

app/about/page.tsx, app/not-found.tsx, app/projects/[id]/page.tsx, components/project/project-detail-tags.tsx, components/project/project-extra-links.tsx, components/site-footer.tsx, styles/globals.css
**General**
**About page** 
**Project page**
=> update FE to design version v1.2

data/projects/maci.ts
- Add website & Twitter
- Update TL;DR
=> Update MACI links & TL;DR

app/i18n/locales/es/about-page.json, app/i18n/locales/es/common.json, app/i18n/locales/es/homepage.json, app/i18n/locales/es/news-section.json, app/i18n/locales/es/projects-page.json, app/i18n/locales/es/resources-page.json, app/i18n/locales/es/what-we-do-section.json
=> added spanish translations

app/i18n/settings.ts, components/project/project-detail-tags.tsx, components/sections/News.tsx, components/site-header-mobile.tsx, components/site-header.tsx
- Language fixes to avoid mismatch on `languages` and `languageList`.
- Add fallbacks for missing values for `news` section
- Fixs links
=> language fixs

app/i18n/locales/vi/about-page.json, app/i18n/locales/vi/common.json, app/i18n/locales/vi/homepage.json, app/i18n/locales/vi/news-section.json, app/i18n/locales/vi/projects-page.json, app/i18n/locales/vi/resources-page.json, app/i18n/locales/vi/what-we-do-section.json
https://github.com/privacy-scaling-explorations/website-v2/issues/125 
Add Vietnamese translation
=> Adding vietnamese

app/[lang]/projects/[id]/page.tsx, components/project/project-card.tsx, data/projects/dsl-working-group.ts, data/projects/ecip-halo2.ts, lib/types.ts
Add projects image placeholder with text for projects where cover image does not exists 
**Project detail**
**Project list**
=> add project image placeholders

app/[lang]/about/page.tsx, app/[lang]/page.tsx, app/[lang]/resources/page.tsx, app/i18n/locales/en/about-page.json, components/ui/label.tsx
Refactor about page to match new design
=> about page new design

app/i18n/locales/de/about-page.json, app/i18n/locales/de/common.json, app/i18n/locales/de/homepage.json, app/i18n/locales/de/news-section.json, app/i18n/locales/de/projects-page.json, app/i18n/locales/de/resources-page.json, app/i18n/locales/de/what-we-do-section.json
This is a first version. Need to go through it again and fine-tune here and there.
=> Add German translation

app/i18n/locales/en/news-section.json, app/i18n/locales/es/news-section.json, app/i18n/locales/it/news-section.json, app/i18n/locales/zh-TW/news-section.json, app/i18n/settings.ts, common/discord.js, components/sections/NewsSection.tsx
=> fix typo + enable german language

app/i18n/locales/fr/about-page.json, app/i18n/locales/fr/common.json, app/i18n/locales/fr/homepage.json, app/i18n/locales/fr/news-section.json, app/i18n/locales/fr/projects-page.json, app/i18n/locales/fr/resources-page.json, app/i18n/locales/fr/what-we-do-section.json, app/i18n/settings.ts
Adding French translation of PSE website. See issue  https://github.com/privacy-scaling-explorations/website-v2/issues/124
=> Adding French

app/[lang]/content/resources.md
I added ECC course by Matan to resources/learning.
=> add ECC course by Matan to resources

app/i18n/settings.ts, components/project/project-card.tsx, config/site.ts, hooks/useAppSettings.ts, lib/fonts.ts, styles/globals.css
=> fix navigation issues

app/i18n/locales/de/common.json, app/i18n/locales/en/common.json, app/i18n/locales/es/common.json
=> feat: update copy

app/layout.tsx
This PR sets the correct `metadataBase` to ensure the proper files are accessed for displaying OpenGraph images.
=> update metadata base

data/projects/anon-klub.ts
AnonKlub is being sunset. (I am the project lead)
So I am updating the project data accordingly
|Before|After|
|---|---|
|![pic-selected-240819-1235-14](https://github.com/user-attachments/assets/fba54748-392c-4b14-992a-6e1a95f0279a)|![pic-selected-240819-1226-09](https://github.com/user-attachments/assets/a2736254-210c-4c98-acc5-3252b01b8aca)|
|![pic-selected-240819-1235-30](https://github.com/user-attachments/assets/d936f63f-0034-4801-a9ba-0508ff731294)|![pic-selected-240819-1226-25](https://github.com/user-attachments/assets/21ce0f02-3d96-4c7b-a910-3c1503c81a7e)|
=> Set anonklub status to `inactive`

data/projects.ts
=> fix MACI Platform

data/projects/maci-platform.ts, data/projects/maci.ts
Add MACI and MACI Platform details
=> chore: update maci and maci platform descriptions

data/events/devcon-7.ts
Fix my social media url because I don't have twitter.
=> fix: @ed255 social media link

app/[lang]/layout.tsx, components/floating-feedback-sidebar.tsx, styles/globals.css
Add `Feedback` button that redirects users to the Discord channel for sharing their feedback.
Links will later be changed to the specific `website-pse` channel
=> feedback button

app/i18n/locales/en/common.json
=> fix maintenance grammar

state/useProjectFiltersState.ts
This PR fixes the following issue https://github.com/privacy-scaling-explorations/pse.dev/issues/272
=> Fix filters out matching results

data/projects/excubiae.ts
The following PR reflects the latest updates on excubiae in order to use the pse.dev project page as default landing page. Further updates will be pushed on this branch in the future. Thanks!
=> Update excubiae project data

data/projects/excubiae.ts, data/projects/maci-platform.ts, data/projects/mpc-stats.ts, data/projects/pse-security.ts, data/projects/rln.ts, data/projects/voice-deck.ts
=> chore: several project status updates

data/projects/maci-platform.ts
=> chore: set maci platform to inactive

data/projects/excubiae.ts
This PR reflects latest changes in terms of documentation & release in the Excubiae project.
=> Reflect latest version on excubiae project

data/projects/circom-mpc.ts
Update project page for Circom-MPC
=> chore: update circom-mpc description

data/projects.ts, data/projects/machina-iO.ts
Adding MachinaIO (pse research) to project list
=> adding iO project to project list

data/projects.ts, data/projects/post-quantum-cryptography.ts
Description:
Added a new project entry for Post-Quantum Cryptography and Ethereum. Included metadata and Markdown-formatted content.
=> adding post quantum team

data/projects/mpc-stats.ts
- Change the org name
- Point website to our docs hosted on github.io
=> docs: update website for MPCStats

data/projects/cursive.ts
Hi! I corrects the GitHub link for the Cursive project in project data file.
=> docs: update Github link in `cursive.ts`

data/projects.ts, data/projects/client-side-proving.ts
Adding the client side proving project page.
=> update csp site

data/projects/zk-id.ts
zkID is not a research project :)
=> Update zkID project to development

articles/announcing-anon-aadhaar.md, articles/announcing-maci-v111.md, articles/release-announcement-maci-10-privacy-scaling-explorations.md, articles/retrospective-summa.md, articles/semaphore-v3-announcement.md
hey team! I found duplicate words and fixed them.
=> docs: remove consecutive duplicate words

app/[lang]/projects/sections/ProjectContent.tsx, data/projects/zk-id.ts
This PR closes https://github.com/privacy-scaling-explorations/pse.dev/issues/340
=> feat: update zkid page

app/i18n/locales/en/blog-page.json, articles/advancing-anon-aadhaar-whats-new-in-v100.md, articles/towards_a_quantum-safe_p2p_for_ethereum.md, components/blog/blog-recent-articles.tsx
=> feat: recent blog styling

app/api/search/route.ts, components/search/search-button.tsx, components/search/search-modal.tsx, hooks/useGlobalSearch.ts
global search refactor using endpoint
=> feat: global search refactor

app/[lang]/layout.tsx, app/layout.tsx
=> feat: general fixes

app/[lang]/blog/page.tsx, app/[lang]/page.tsx, app/[lang]/projects/sections/ProjectContent.tsx, app/api/articles/route.ts, app/api/search/indexes/route.ts, app/i18n/locales/en/research-page.json, app/layout.tsx, components/blog/ArticlesList.tsx, components/blog/article-in-evidance-card.tsx, components/blog/article-list-card.tsx, components/blog/blog-recent-articles.tsx, components/blog/project-blog-articles.tsx, components/search/search-modal.tsx, tailwind.config.js
=> feat: blog page redesign

app/[lang]/page.tsx, app/api/news/route.ts, app/api/youtube/route.ts, app/i18n/locales/en/homepage.json, components/blog/ArticlesList.tsx, components/icons.tsx, components/sections/HomepageVideoFeed.tsx, components/sections/WhatWeDo.tsx, components/ui/button.tsx, hooks/useYoutube.ts, next.config.mjs
=> feat: youtube feed

articles/bls-wallet-bundling-up-data-privacy-scaling-explorations.md
=> Update TLDR bls-wallet-bundling-up-data-privacy-scaling-explorations.md

articles/semaphore-v2-is-live-privacy-scaling-explorations.md
=> Update TLDR semaphore-v2-is-live-privacy-scaling-explorations.md

app/[lang]/blog/[slug]/page.tsx, articles/reflecting-on-maci-platform.md, components/blog/article-list-card.tsx, components/blog/blog-article-related-projects.tsx, components/blog/blog-content.tsx, components/blog/project-blog-articles.tsx, components/wiki-side-navigation.tsx, hooks/useGetProjectRelatedArticles.ts
Display a list of related projects at the end of each blog post
=> feat: auto-link to projects page from blog posts

articles/self-sovereign-identity-programmable-cryptography-challenges-ahead.md, components/ui/markdown.tsx, data/projects/zk-id.ts
General updates on zk-id project
=> feat: zk-id updates

articles/post-quantum-signature-aggregation-with-falcon-and-LaBRADOR.md
@kalidiagne I am not sure if I am supposed to add an image or not please let me know.
=> add pq post

data/projects/machina-iO.ts, data/projects/post-quantum-cryptography.ts
adding links to blogposts for io and pq projects
=> adding links

articles/release-announcement-maci-10-privacy-scaling-explorations.md
Hey team! Fixed errors in release-announcement-maci-10-privacy-scaling-explorations.md
`particulary` - `particularly`
`flexiblity` - `flexibility`
=> fix spelling issues 

data/projects/anon-aadhaar.ts
fixed typo in data/projects/anon-aadhaar.ts
Passord - Password
=> fix typo anon-aadhaar.ts

app/(pages)/blog/[slug]/page.tsx, app/(pages)/projects/sections/ProjectContent.tsx, app/layout.tsx, components/blog/articles-list.tsx, config/site.ts
=> General fixes part 7

content/projects/pir-scaling-semaphore.md, content/projects/plasma-fold.md
=> chore: fix typos

components/ui/markdown.tsx
- related PRs: #526 
Footnotes were breaking when using double dollar signs (`$$`) for math blocks, but worked correctly with single dollar signs (`$`). This happened because:
1. **Content Splitting**: The original implementation split content by `$$` regex and processed each part with separate `ReactMarkdown` instances
2. **Cross-Reference Breaking**: Footnotes are cross-references that need to be resolved within a single markdown processing context - when split, footnote references `[^1]` in one part couldn't find their definitions `[^1]: ...` in another part
Check out the current blog posts, we can see that footnotes disappear whenever `$$` math blocks are used
- https://pse.dev/blog/mopro-metal-msm-v2
- https://pse.dev/blog/a-trustless-and-simple-14k-tps-payment-l2-from-plasma-and-clie …
=> fix: parse footnotes and math blocks correctly

config/site.ts, content/articles/announcing-maci-v111.md, content/articles/hello-world-the-first-signs-of-practical-io.md, content/articles/retrospective-trusted-setups-and-p0tion-project.md, content/articles/semaphore-community-grants.md, content/articles/zkopru-wat-y-wen-privacy-scaling-explorations.md, content/events/devcon-7.ts, content/projects/vOPRF.md, content/projects/zk-id.md
Might have missed a few references? Please check my work @kalidiagne :)
=> Update Twitter/X links to new handle
